project_name: togomak
builds:
  - main: ./cmd/togomak
    id: togomak
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nfpms:
- maintainer: Srevin Saju
  description: A CI/CD which works everywhere, even on your local environment.
  homepage: https://gitlab.com/srevinsaju/togomak
  license: MPL-2.0
  formats:
  - deb
  - rpm
  - apk

