togomak {
  version = 2
  behavior {
    disable_concurrency = true
  }
}

locals {
  readme = "${path.module}/README.md"
}


stage "header" {
  script = <<-EOT
  rm ${local.readme}
  echo '# Examples' | tee -a ${local.readme}
  echo 'The following are a list of examples. This list is autogenerated using `togomak --disable-concurrency` at [togomak](./togomak.hcl).' | tee -a ${local.readme}
  echo '' | tee -a ${local.readme}
  EOT
}

stage "generate" {
  depends_on = [stage.header]
  for_each   = fileset(".", "*/.meta.yaml")
  script     = <<-EOT
  echo '## ${yamldecode(file(each.key)).title}' | tee -a ${local.readme}
  echo '${yamldecode(file(each.key)).description}' | tee -a ${local.readme}
  echo '[Example](./${dirname(each.key)})' | tee -a ${local.readme}
  echo '' | tee -a ${local.readme}
  EOT 
}
