package ci

//ctx = context.WithValue(ctx, c.TogomakContextCi, cfg.Behavior.Ci)
//ctx = context.WithValue(ctx, c.TogomakContextUnattended, cfg.Behavior.Unattended)
//ctx = context.WithValue(ctx, c.TogomakContextLogger, logger)
//ctx = context.WithValue(ctx, c.TogomakContextBootTime, time.Now())
//ctx = context.WithValue(ctx, c.TogomakContextPipelineId, pipelineId)
//ctx = context.WithValue(ctx, c.TogomakContextOwd, cfg.Owd)
//ctx = context.WithValue(ctx, c.TogomakContextCwd, cwd)
//ctx = context.WithValue(ctx, c.TogomakContextHostname, cfg.Hostname)
//ctx = context.WithValue(ctx, c.TogomakContextUsername, cfg.User)
//ctx = context.WithValue(ctx, c.TogomakContextPipelineFilePath, cfg.Pipeline.FilePath)
//ctx = context.WithValue(ctx, c.TogomakContextPipelineDryRun, cfg.Pipeline.DryRun)
//ctx = context.WithValue(ctx, c.TogomakContextPipelineTmpDir, tempDir)
//ctx = context.WithValue(ctx, c.TogomakContextHclDiagWriter, diagnosticTextWriter)
